### PR TITLE
Update to version 1.0.317301

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Looks like the build has changed:
```
+ export DisableArcade=1
+ DisableArcade=1
+ export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
+ DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
+ dotnet run --project /home/conda/feedstock_root/build_artifacts/dotnet-interactive_1653735242630/work/src/interface-generator --out-file /home/conda/feedstock_root/build_artifacts/dotnet-interactive_1653735242630/work/src/dotnet-interactive-vscode/common/interfaces/contracts.ts

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.202

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
File does not exist: '/home/conda/feedstock_root/build_artifacts/dotnet-interactive_1653735242630/work/src/dotnet-interactive-vscode/common/interfaces/contracts.ts'.

Description:

Usage:
  Microsoft.DotNet.Interactive.InterfaceGen.App [options]

Options:
  --out-file <out-file> (REQUIRED)  Location to write the generated interface file
  --version                         Show version information
  -?, -h, --help                    Show help and usage information
```

**Comment by acesnik** [comment]
I got this to work recently on my machine (macos) with 
```
dotnet tool install --global Microsoft.dotnet-interactive --version 1.0.410202
dotnet interactive jupyter install
```

Does this install the kernels in the wrong place?

**Comment by dhirschfeld** [comment]
> *Does this install the kernels in the wrong place?*

Sorry, I should have closed this old PR. I fixed the build and updated to the latest in #10

**Comment by dhirschfeld** [comment]
This should work fine with something like:
```
mamba install python jupyterlab dotnet dotnet-interactive
```

The [kernels](https://github.com/conda-forge/dotnet-interactive-feedstock/tree/main/recipe/kernels) are installed into the usual `share/jupyter/kernels` location:
https://github.com/conda-forge/dotnet-interactive-feedstock/blob/83e2c2dfa8b9714f329ce15493fb4739544582be/recipe/build.sh#L28

At least for me, it seems to work well and the kernels are automatically picked up. If you have issues let me know and I can look into it...

**Comment by dhirschfeld** [comment]
```
❯ jupyter lab --ip='0.0.0.0' --ServerApp.token= --ServerApp.password=
```
<br>

image

**Pull request closed without merging**
